security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$XSVbjBvtrT6IgdnL0W1.SeaHbb8yLfDZwgTnn7i40Hftb/mZfPrhK
                        roles: 'ROLE_ADMIN'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin/
            http_basic: true
            provider: in_memory
        api:
            pattern: ^/api/
            guard:
                authenticators:
                    - App\Security\Authenticator\KeycloakAuthenticator
            stateless: true
        main:
            anonymous: ~
    access_control:
        - { path: ^/api/, roles: ROLE_API }
        - { path: ^/admin/, roles: ROLE_ADMIN }
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
