vich_uploader:
    db_driver: orm

    mappings:
        media_object:
            uri_prefix: /files
            upload_destination: '%kernel.project_dir%/public/files'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
